version: '3.4'
services:
  person-api:
    image: person-api
    container_name: "person-api"
    restart: on-failure
    build:
      context: .
      dockerfile: back-end/Dockerfile
    ports:
      - 8080:8080
    command: mvn spring-boot:run